### ISSUE TITLE
Platform not found: climate.e_thermostaat

### ISSUE THREAD

**Issue by remb0** [gerard33/home-assistant#7]
I have run this great component for months but now it saying:
Platform not found: climate.e_thermostaat

I have made the folder and named the files like the readme.  I have also paid for a year :)   the app and website are still working.

what can I do?

**Comment by remb0** [comment]
in mijn logs zie ik onderstaande melding. Ik draai hass.io image op mijn pi
[code]
2019-03-07 21:59:39 ERROR (SyncWorker_17) [homeassistant.loader] Error loading custom_components.climate.e_thermostaat. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/climate/e_thermostaat.py", line 10, in <module>
    from homeassistant.components.climate import (
ImportError: cannot import name 'SUPPORT_TARGET_TEMPERATURE' from 'homeassistant.components.climate' (/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py)
2019-03-07 21:59:39 ERROR (SyncWorker_17) [homeassistant.loader] Unable to find platform e_thermostaat.
[/code]

**Comment by gerard33** [comment]
It's fixed in d5d5c97.
Please mention next time that you had the issue after upgrading HA to 0.89, that makes it a bit easier to pinpoint the issue :grinning:

**Comment by remb0** [comment]
thank you so much!  I will do next time, I promise :)
